[program:ark-static]
command=/usr/sbin/nginx -c /opt/ark-static/nginx.conf -g "daemon off;"
directory=/opt/ark-static
autostart=true
autorestart=true
startsecs=3
startretries=3
stopsignal=QUIT
stopwaitsecs=30
stopasgroup=false
killasgroup=true
stdout_logfile=/opt/ark-static/log/access.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/opt/ark-static/log/error.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=3
