import { test } from 'node:test';
import assert from 'node:assert/strict';
import { chmod, copyFile, lstat, mkdir, mkdtemp, readFile, rm, symlink, link, writeFile } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { createServer } from 'node:net';
import { setTimeout as delay } from 'node:timers/promises';
import { request } from 'node:http';
import { VENDOR_FILES, VENDOR_REWRITES, rewriteBare } from '../../../tools/vendor.mjs';
import { AUDIO_EXTS } from '../../../shared/media.js';
import { buildFonts, FONTS } from '../../../tools/assets/fonts.mjs';
import { AUDIO_MIME, FONT_CSS_SHA256, FONT_CSS_RELATIVE_SHA256, patchFonts, patchHooks, mediaMappings, nginxIncludes,
  prepareStaticRelease, verifyStaticRelease } from './prepare-static-release.mjs';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const REVISION = '1'.repeat(40);
const RELEASE = 'workers-test-r1';
const FONT_CSS = `/* Generated by tools/fetch-assets.mjs — do not edit.
 * Bender (c) Jovanny Lemonad / Oleg Zhuravlev, Gladkikh Ivan — free font.
 * Novecento Wide (c) Jan Tonellato / Synthview — free font.
 * Usage: font-family: Bender, Rajdhani, 'Noto Sans SC', sans-serif;
 *        font-family: 'Novecento Wide', 'Saira Condensed', 'Noto Sans SC', sans-serif; */

@font-face {
  font-family: 'Bender';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/bender-regular.woff2') format('woff2'),
       url('/fonts/bender-regular.otf') format('opentype');
}

@font-face {
  font-family: 'Bender';
  font-style: normal;
  font-weight: 300;
  font-display: swap;
  src: url('/fonts/bender-light.woff2') format('woff2'),
       url('/fonts/bender-light.ttf') format('truetype');
}

@font-face {
  font-family: 'Novecento Wide';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/novecento-wide-normal.woff2') format('woff2'),
       url('/fonts/novecento-wide-normal.otf') format('opentype');
}
`;
const FONT_NAMES = ['bender-regular.woff2', 'bender-regular.otf', 'bender-light.woff2', 'bender-light.ttf',
  'novecento-wide-normal.woff2', 'novecento-wide-normal.otf'];
const AUDIO_DATA = Buffer.from('synthetic test audio 0123456789');
const sha256 = (data) => createHash('sha256').update(data).digest('hex');
async function put(path, data) { await mkdir(dirname(path), { recursive: true }); await writeFile(path, data); }
async function absent(path) { await assert.rejects(lstat(path), { code: 'ENOENT' }); }

async function fixture(t) {
  const base = await mkdtemp(join(tmpdir(), 'ark-static-release-'));
  // Nginx workers need to traverse mkdtemp's normally private directory for the optional smoke test.
  await chmod(base, 0o755);
  t.after(() => rm(base, { recursive: true, force: true }));
  const source = join(base, 'source');
  const output = join(base, 'prepared');
  await put(join(source, 'package.json'), JSON.stringify({ type: 'module', version: '0.1.2', dependencies: { preact: '^1.2.3' } }));
  const packages = { '': { version: '0.1.2', dependencies: { preact: '^1.2.3' } } };
  for (const [from, name] of VENDOR_FILES) {
    const packageName = from.match(/^node_modules\/([^/]+)\//)[1];
    const key = 'node_modules/' + packageName;
    packages[key] = { version: '1.2.3', integrity: 'sha512-test-' + packageName };
    await put(join(source, key, 'package.json'), JSON.stringify({ version: '1.2.3' }));
    const contents = name === 'hooks.module.js' ? 'import{options as n}from"preact";export const hooks=n;' : `export const testName=${JSON.stringify(name)};`;
    await put(join(source, from), contents);
    await put(join(source, 'public/vendor', name), VENDOR_REWRITES[name] ? rewriteBare(contents, VENDOR_REWRITES[name]) : contents);
  }
  await put(join(source, 'package-lock.json'), JSON.stringify({ version: '0.1.2', packages }));
  await put(join(source, 'node_modules/.package-lock.json'), JSON.stringify({ packages }));
  await mkdir(join(source, 'tools'), { recursive: true });
  await copyFile(join(REPO, 'tools/vendor.mjs'), join(source, 'tools/vendor.mjs'));
  await put(join(source, 'shared/media.js'), `export const MEDIA_PREFIX='/media/';export const AUDIO_EXTS=${JSON.stringify(AUDIO_EXTS)};`);
  await put(join(source, 'data/assets.json'), JSON.stringify({ version: 1, hash: 'test-manifest', stats: { files: 3 },
    audio: ['/assets/audio/bgm/theme.mp3', '/assets/audio/bgm/theme.ogg'], art: '/assets/ui/[opt]image.png',
    fonts: { css: '/fonts/fonts.css', faces: FONT_NAMES.map((f) => '/fonts/' + f) } }));
  await put(join(source, 'data/local-assets.json'), JSON.stringify({ groups: { model: '/assets/local/model.obj' } }));
  await put(join(source, 'public/assets/ui/[opt]image.png'), 'synthetic image');
  await put(join(source, 'public/assets/local/model.obj'), 'synthetic model');
  await put(join(source, 'public/assets/local/materials.json'), '{"test":true}');
  await put(join(source, 'public/assets/audio/bgm/theme.mp3'), AUDIO_DATA);
  await put(join(source, 'public/assets/audio/bgm/theme.ogg'), 'alternate audio');
  for (const ext of AUDIO_EXTS) await put(join(source, 'public/assets/audio/sfx/test' + ext.slice(1) + ext), AUDIO_DATA);
  await put(join(source, 'public/fonts/fonts.css'), FONT_CSS);
  for (const name of FONT_NAMES) await put(join(source, 'public/fonts', name), 'synthetic font');
  // These deliberately never belong to the public static release.
  await put(join(source, 'public/js/gate.js'), 'private game code');
  await put(join(source, 'public/css/gate.css'), 'private application CSS');
  await put(join(source, 'data/private.json'), '{"private":true}');
  return { base, source, output, release: RELEASE, sourceRevision: REVISION };
}

test('exact current font CSS and single-instance hooks patches reject drift', () => {
  assert.equal(sha256(FONT_CSS), FONT_CSS_SHA256);
  const patched = patchFonts(Buffer.from(FONT_CSS)).toString();
  assert.equal((patched.match(/url\('\.\//g) || []).length, 6);
  assert.doesNotMatch(patched, /url\('\/fonts\//);
  assert.throws(() => patchFonts(Buffer.from(FONT_CSS + '\n')), /Unexpected fonts/);
  assert.equal(sha256(patched), FONT_CSS_RELATIVE_SHA256);
  assert.equal(patchFonts(Buffer.from(patched)).toString(), patched, 'reviewed relative output is idempotent');
  for (const drift of [patched + '\n', patched.replace('400', '500'), patched.replace('./bender-regular.woff2', './other.woff2')]) {
    assert.throws(() => patchFonts(Buffer.from(drift)), /Unexpected fonts/);
  }
  const hooks = patchHooks(Buffer.from('import{options as n}from"./preact.module.js";export const hooks=n;')).toString();
  assert.match(hooks, /from"https:\/\/ark-proto\.stardust\.matce\.cn\/vendor\/preact\.module\.js"/);
  for (const bad of ['import{options as n}from"preact";', hooks,
    'import{options as n}from"./preact.module.js";import{h}from"./preact.module.js";',
    'import{options as n}from"./preact.module.js";import{h}from"./other.js";']) {
    assert.throws(() => patchHooks(Buffer.from(bad)), /Unexpected hooks/);
  }
});

test('font generator emits the exact reviewed relative CSS without changing manifest URL semantics', async (t) => {
  const f = await fixture(t);
  const fontsDir = join(f.base, 'generated-fonts');
  const sfnt = Buffer.alloc(84, 0);
  sfnt.writeUInt32BE(0x4f54544f, 0); sfnt.writeUInt16BE(1, 4);
  sfnt.write('head', 12, 'latin1'); sfnt.writeUInt32BE(28, 20); sfnt.writeUInt32BE(54, 24);
  for (const font of FONTS) await put(join(fontsDir, `${font.name}.${font.ext}`), sfnt);
  const generated = await buildFonts(fontsDir, () => {});
  assert.deepEqual(generated.errors, []); assert.equal(sha256(generated.css), FONT_CSS_RELATIVE_SHA256);
  assert.equal(generated.css, patchFonts(Buffer.from(FONT_CSS)).toString());
  for (const font of FONTS) {
    assert.equal(generated.files[font.name].original, `/fonts/${font.name}.${font.ext}`);
    assert.equal(generated.files[font.name].woff2, `/fonts/${font.name}.woff2`);
  }
  assert.equal((await buildFonts(fontsDir, () => {})).css, generated.css);
  assert.equal(new URL('./bender-regular.woff2', 'https://static.test/releases/material-r1/fonts/fonts.css').pathname,
    '/releases/material-r1/fonts/bender-regular.woff2');
});

test('root preparation accepts reviewed relative fonts and verifies root hooks identity, including CLI', async (t) => {
  const f = await fixture(t);
  await put(join(f.source, 'public/fonts/fonts.css'), patchFonts(Buffer.from(FONT_CSS)));
  const manifest = await prepareStaticRelease(f);
  const fontPatch = manifest.patches.find(({ path }) => path === 'fonts/fonts.css');
  assert.equal(fontPatch.beforeSha256, FONT_CSS_RELATIVE_SHA256);
  assert.equal(fontPatch.afterSha256, FONT_CSS_RELATIVE_SHA256);
  const hooks = await readFile(join(f.output, 'releases', RELEASE, 'vendor/hooks.module.js'), 'utf8');
  assert.match(hooks, /from"https:\/\/ark-proto\.stardust\.matce\.cn\/vendor\/preact\.module\.js"/);
  assert.deepEqual(await verifyStaticRelease(f.output), manifest);
  const output2 = join(f.base, 'cli-root');
  const cli = spawnSync(process.execPath, [join(REPO, 'deploy/stardust/tools/prepare-static-release.mjs'),
    '--source', f.source, '--out', output2, '--release', RELEASE, '--revision', REVISION], { encoding: 'utf8' });
  assert.equal(cli.status, 0, cli.stderr);
  assert.deepEqual(await verifyStaticRelease(output2), manifest);
});

test('offline preparation copies only public resources, records hashes/patches and verifies reproducibly', async (t) => {
  const f = await fixture(t);
  const manifest = await prepareStaticRelease(f);
  assert.equal(manifest.appVersion, '0.1.2');
  assert.equal(manifest.sourceRevision, REVISION);
  assert.equal(manifest.patches.length, 2);
  assert.equal(new Set(manifest.inputs.map((entry) => entry.path)).size, manifest.inputs.length);
  assert.equal(manifest.media.filter(({ requestedExtension }) => !requestedExtension).length, AUDIO_EXTS.length + 1);
  assert.equal(manifest.media.length, (AUDIO_EXTS.length + 1) ** 2);
  assert.equal(manifest.nginx.length, 4);
  assert.match(await readFile(join(f.output, 'SHA256SUMS'), 'utf8'), /nginx\/game-static-locations\.conf/);
  assert.equal(manifest.media.find((entry) => entry.url === '/media/bgm/theme').file, 'assets/audio/bgm/theme.mp3');
  for (const entry of manifest.files) {
    assert.match(entry.path, /^(assets|fonts|vendor)\//);
    const file = join(f.output, 'releases', RELEASE, entry.path);
    const data = await readFile(file);
    assert.equal(data.length, entry.bytes);
    assert.equal(sha256(data), entry.sha256);
    assert.equal((await lstat(file)).mode & 0o777, 0o644);
  }
  assert.equal((await readFile(join(f.source, 'public/fonts/fonts.css'), 'utf8')), FONT_CSS);
  assert.match(await readFile(join(f.source, 'public/vendor/hooks.module.js'), 'utf8'), /from"\.\/preact\.module\.js"/);
  await absent(join(f.output, 'releases', RELEASE, 'js'));
  await absent(join(f.output, 'releases', RELEASE, 'data'));
  assert.deepEqual(await verifyStaticRelease(f.output), manifest);
  const output2 = join(f.base, 'prepared2');
  assert.deepEqual(await prepareStaticRelease({ ...f, output: output2 }), manifest);
  assert.equal(await readFile(join(output2, 'SHA256SUMS'), 'utf8'), await readFile(join(f.output, 'SHA256SUMS'), 'utf8'));
  const verify = spawnSync(process.execPath, [join(REPO, 'deploy/stardust/tools/prepare-static-release.mjs'), '--verify', f.output], { encoding: 'utf8' });
  assert.equal(verify.status, 0, verify.stderr);
});

test('release/revision validation and existing output refusal leave existing directories untouched', async (t) => {
  const f = await fixture(t);
  for (const release of ['../escape', 'future.release', 'x;return 200', '']) {
    await assert.rejects(prepareStaticRelease({ ...f, release }), /Release must/);
    await absent(f.output);
  }
  await assert.rejects(prepareStaticRelease({ ...f, sourceRevision: 'HEAD' }), /Revision must/);
  await mkdir(f.output);
  await put(join(f.output, 'keep'), 'keep');
  await assert.rejects(prepareStaticRelease(f), { code: 'EEXIST' });
  assert.equal(await readFile(join(f.output, 'keep'), 'utf8'), 'keep');
});

test('missing manifest references, empty files and changed CSS fail before output exists', async (t) => {
  for (const change of ['missing', 'empty', 'css']) {
    const f = await fixture(t);
    if (change === 'missing') await rm(join(f.source, 'public/assets/local/model.obj'));
    if (change === 'empty') await put(join(f.source, 'public/assets/ui/[opt]image.png'), '');
    if (change === 'css') await put(join(f.source, 'public/fonts/fonts.css'), FONT_CSS.replace('400', '500'));
    await assert.rejects(prepareStaticRelease(f), /missing\/empty|nonempty|Unexpected fonts/);
    await absent(f.output);
  }
});

test('stale vendor, package versions and hidden lockfile integrity fail closed', async (t) => {
  for (const change of ['vendor', 'version', 'integrity', 'lock-version']) {
    const f = await fixture(t);
    if (change === 'vendor') await put(join(f.source, 'public/vendor/preact.module.js'), 'stale vendor');
    if (change === 'version') await put(join(f.source, 'node_modules/preact/package.json'), '{"version":"9.0.0"}');
    if (change === 'integrity') {
      const path = join(f.source, 'node_modules/.package-lock.json');
      const lock = JSON.parse(await readFile(path, 'utf8'));
      lock.packages['node_modules/preact'].integrity = 'sha512-mismatch';
      await put(path, JSON.stringify(lock));
    }
    if (change === 'lock-version') {
      const path = join(f.source, 'package-lock.json');
      const lock = JSON.parse(await readFile(path, 'utf8')); lock.version = '0.1.1';
      await put(path, JSON.stringify(lock));
    }
    await assert.rejects(prepareStaticRelease(f), /differs from the locked|does not match package-lock|do not match/);
    await absent(f.output);
  }
});

test('symlink/hardlink files, symlink directories, dotfiles and application code cannot be published', async (t) => {
  for (const change of ['symlink', 'hardlink', 'directory', 'public', 'dependency', 'dotfile', 'code', 'extra-vendor', 'unsafe-name']) {
    const f = await fixture(t);
    const image = join(f.source, 'public/assets/ui/[opt]image.png');
    if (change === 'symlink' || change === 'hardlink') {
      await rm(image);
      await (change === 'symlink' ? symlink : link)(join(f.source, 'public/js/gate.js'), image);
    }
    if (change === 'directory') {
      await rm(join(f.source, 'public/assets/local'), { recursive: true });
      await symlink(join(f.source, 'data'), join(f.source, 'public/assets/local'));
    }
    if (change === 'public') {
      await rm(join(f.source, 'public'), { recursive: true });
      await symlink(join(f.source, 'data'), join(f.source, 'public'));
    }
    if (change === 'dependency') {
      await rm(join(f.source, 'node_modules/preact'), { recursive: true });
      await symlink(join(f.source, 'node_modules/htm'), join(f.source, 'node_modules/preact'));
    }
    if (change === 'dotfile') await put(join(f.source, 'public/assets/.secret.json'), 'secret');
    if (change === 'code') await put(join(f.source, 'public/assets/app.js'), 'private code');
    if (change === 'extra-vendor') await put(join(f.source, 'public/vendor/server.js'), 'private server');
    if (change === 'unsafe-name') await put(join(f.source, 'public/assets/ui/a;return 200.png'), 'art');
    await assert.rejects(prepareStaticRelease(f), /regular|directory|Unsafe|non-art\/code|Unexpected vendor/);
    await absent(f.output);
  }
});

test('audio stems stay extensionless; explicit suffixes match upstream requested-first/fallback resolution', () => {
  const files = AUDIO_EXTS.map((ext) => ({ path: 'assets/audio/bgm/theme' + ext }));
  const routes = mediaMappings(files.reverse(), AUDIO_EXTS, '/media/');
  assert.equal(routes.length, AUDIO_EXTS.length + 1);
  assert.deepEqual(routes.find(({ url }) => url === '/media/bgm/theme'),
    { url: '/media/bgm/theme', requestedExtension: '', file: 'assets/audio/bgm/theme.mp3', ext: '.mp3', mime: 'audio/mpeg' });
  for (const ext of AUDIO_EXTS) assert.equal(routes.find(({ requestedExtension }) => requestedExtension === ext).ext, ext);
  for (const availableExts of [['.mp3', '.ogg'], ['.ogg'], ['.m4a', '.opus'], ['.wav']]) {
    const available = availableExts.map((ext) => ({ path: 'assets/audio/bgm/theme' + ext }));
    for (const route of mediaMappings(available, AUDIO_EXTS, '/media/')) {
      const requested = route.requestedExtension;
      const order = requested ? [requested, ...AUDIO_EXTS.filter((ext) => ext !== requested)] : AUDIO_EXTS;
      const expected = order.find((ext) => availableExts.includes(ext));
      assert.equal(route.file, 'assets/audio/bgm/theme' + expected, route.url);
      assert.equal(route.mime, AUDIO_MIME[expected], route.url);
      if (!requested) assert.doesNotMatch(route.url, /\.(mp3|m4a|aac|ogg|oga|opus|wav)$/);
    }
  }
  assert.throws(() => mediaMappings(files, ['.flac'], '/media/'), /Unexpected shared/);
  assert.throws(() => mediaMappings(files, AUDIO_EXTS, '/new-media/'), /Unexpected shared/);
  assert.throws(() => mediaMappings([{ path: 'assets/audio/theme.MP3' }], AUDIO_EXTS, '/media/'), /Unsupported/);
  assert.throws(() => mediaMappings([{ path: 'assets/audio/theme.mp3.ogg' }], AUDIO_EXTS, '/media/'), /still ends/);
});

test('generated snippets are staged, whitelist resources, preserve extensionless redirects and set real-file MIME', async (t) => {
  const f = await fixture(t);
  const manifest = await prepareStaticRelease(f);
  const includes = nginxIncludes(manifest);
  assert.match(includes['static-files.conf'], /map \$uri \$ark_static_[a-f0-9]+_file/);
  assert.match(includes['static-files.conf'], /default "";/);
  assert.match(includes['static-files.conf'], /\[opt\]image\.png/);
  assert.doesNotMatch(includes['static-files.conf'], /gate\.js|private\.json|\/data\//);
  assert.match(includes['static-cache.conf'], /200\|206\|304/);
  assert.match(includes['static-locations.conf'], /alias \/srv\/ark-static\/releases\/workers-test-r1\/assets\/audio\/bgm\/theme\.mp3;/);
  assert.match(includes['static-locations.conf'], /types \{ \}\n    default_type audio\/mpeg;/);
  assert.doesNotMatch(includes['static-locations.conf'], /return 30[1278]/);
  assert.match(includes['static-locations.conf'], /disable_symlinks on;/);
  for (const dir of ['assets', 'fonts', 'vendor', 'media']) assert.match(includes['game-static-locations.conf'], new RegExp(`location \\^~ /${dir}/`));
  assert.match(includes['game-static-locations.conf'], /releases\/workers-test-r1\$request_uri/);
  assert.match(includes['game-static-locations.conf'], /STAGED/);
  const baseline = await readFile(join(REPO, 'deploy/stardust/static/nginx.conf'), 'utf8');
  for (const dir of ['cache', 'http', 'locations']) assert.ok(baseline.includes(`/opt/ark-static/generated/${dir}/*.conf`));
  assert.match(baseline, /releases\/8cd6491/);
});

test('verification detects hash edits, extra resources, symlinks and config changes', async (t) => {
  for (const change of ['bytes', 'extra', 'symlink', 'include', 'sums']) {
    const f = await fixture(t);
    await prepareStaticRelease(f);
    const root = join(f.output, 'releases', RELEASE);
    if (change === 'bytes') await put(join(root, 'assets/audio/bgm/theme.mp3'), 'corrupted');
    if (change === 'extra') await put(join(root, 'assets/extra.json'), '{}');
    if (change === 'symlink') {
      await rm(join(root, 'assets/audio/bgm/theme.mp3'));
      await symlink(join(f.source, 'public/assets/audio/bgm/theme.mp3'), join(root, 'assets/audio/bgm/theme.mp3'));
    }
    if (change === 'include') await put(join(f.output, 'nginx/static-cache.conf'), '# corrupted');
    if (change === 'sums') await put(join(f.output, 'SHA256SUMS'), 'corrupted');
    await assert.rejects(verifyStaticRelease(f.output), /mismatch|differs|regular/);
  }
});

async function freePort() {
  const server = createServer();
  await new Promise((resolve, reject) => server.listen(0, '127.0.0.1', resolve).once('error', reject));
  const port = server.address().port;
  await new Promise((resolve) => server.close(resolve));
  return port;
}
async function rawGet(port, path) {
  return new Promise((resolve, reject) => {
    const req = request({ host: '127.0.0.1', port, path }, (res) => {
      let body = ''; res.setEncoding('utf8'); res.on('data', (chunk) => { body += chunk; });
      res.on('end', () => resolve({ status: res.statusCode, body, headers: res.headers }));
    });
    req.on('error', reject); req.end();
  });
}

function nginxBinary(t) {
  const nginx = process.env.NGINX_BIN || 'nginx';
  const version = spawnSync(nginx, ['-v'], { encoding: 'utf8' });
  if (version.error?.code === 'ENOENT' && !process.env.NGINX_BIN) { t.skip('Nginx is not installed; set NGINX_BIN to run the real route smoke'); return null; }
  assert.equal(version.status, 0, version.stderr || String(version.error));
  return nginx;
}

async function withNginx(nginx, f, manifest, callback) {
  const includes = nginxIncludes(manifest, { staticRoot: f.output });
  for (const [name, contents] of Object.entries(includes)) await put(join(f.base, name), contents);
  const port = await freePort(); const gamePort = await freePort();
  const config = (await readFile(join(REPO, 'deploy/stardust/static/nginx.conf'), 'utf8'))
    .replace(/^user .*;\n/m, '').replace('worker_processes 10;', 'worker_processes 1;')
    .replace('pid /run/ark-static-nginx.pid;', `pid ${f.base}/nginx.pid;`)
    .replace('error_log /dev/stderr warn;', `error_log ${f.base}/nginx-error.log warn;`)
    .replace('include /etc/nginx/mime.types;', process.env.NGINX_MIME_TYPES ? `include ${process.env.NGINX_MIME_TYPES};` : 'types { image/png png; text/css css; application/javascript js; audio/mpeg mp3; }')
    .replace('http {', `http {\n    client_body_temp_path ${f.base}/body;\n    proxy_temp_path ${f.base}/proxy;\n    fastcgi_temp_path ${f.base}/fastcgi;\n    uwsgi_temp_path ${f.base}/uwsgi;\n    scgi_temp_path ${f.base}/scgi;`)
    .replace('access_log /dev/stdout asset;', 'access_log off;')
    .replace('include /opt/ark-static/generated/cache/*.conf;', `include ${f.base}/static-cache.conf;`)
    .replace('include /opt/ark-static/generated/http/*.conf;', `include ${f.base}/static-files.conf;`)
    .replace('include /opt/ark-static/generated/locations/*.conf;', `include ${f.base}/static-locations.conf;`)
    .replace('listen 3000 ssl http2;', `listen 127.0.0.1:${port};`)
    .replace('root /srv/ark-static;', `root ${f.output};`)
    .replace(/^\s*ssl_[^\n]*\n/gm, '')
    .replace(/\n}\s*$/, `\n    server { listen 127.0.0.1:${gamePort}; include ${f.base}/game-static-locations.conf; location / { return 401; } }\n}\n`);
  const configPath = join(f.base, 'nginx.conf'); await put(configPath, config);
  const syntax = spawnSync(nginx, ['-t', '-e', 'stderr', '-p', f.base + '/', '-c', configPath], { encoding: 'utf8' });
  assert.equal(syntax.status, 0, syntax.stderr);
  assert.doesNotMatch(syntax.stderr, /could not build.*map_hash/, syntax.stderr);
  const child = spawn(nginx, ['-e', 'stderr', '-p', f.base + '/', '-c', configPath, '-g', 'daemon off;'], { stdio: ['ignore', 'ignore', 'pipe'] });
  let stderr = ''; child.stderr.on('data', (data) => { stderr += data; });
  try {
    const origin = `http://127.0.0.1:${port}`;
    let ready = false;
    for (let i = 0; i < 100; i++) {
      if (child.exitCode !== null) throw new Error('Nginx exited before ready: ' + stderr);
      try { ready = (await fetch(origin + '/healthz')).ok; if (ready) break; } catch { /* awaiting local readiness */ }
      await delay(25);
    }
    assert.ok(ready, 'Nginx was not ready: ' + stderr);
    await callback({ origin, port, gamePort });
  } finally {
    child.kill('SIGQUIT');
    if (child.exitCode === null) await Promise.race([new Promise((resolve) => child.once('exit', resolve)), delay(2000)]);
    if (child.exitCode === null) child.kill('SIGKILL');
  }
}

test('local Nginx smoke: extensionless MIME/HEAD/Range/ETag/CORS/cache and publication boundaries', { timeout: 20000 }, async (t) => {
  const nginx = nginxBinary(t); if (!nginx) return;
  const f = await fixture(t);
  const manifest = await prepareStaticRelease(f);
  await withNginx(nginx, f, manifest, async ({ origin, port, gamePort }) => {
    const url = origin + `/releases/${RELEASE}/media/bgm/theme`;
    const get = await fetch(url);
    assert.equal(get.status, 200); assert.equal(get.url, url);
    assert.equal(get.headers.get('content-type'), 'audio/mpeg');
    assert.equal(get.headers.get('access-control-allow-origin'), '*');
    assert.equal(get.headers.get('access-control-allow-credentials'), null);
    assert.match(get.headers.get('cache-control'), /immutable/);
    assert.equal(get.headers.get('accept-ranges'), 'bytes');
    assert.equal(get.headers.get('x-content-type-options'), 'nosniff');
    assert.deepEqual(Buffer.from(await get.arrayBuffer()), AUDIO_DATA);
    const etag = get.headers.get('etag'); assert.ok(etag);
    const head = await fetch(url, { method: 'HEAD' });
    assert.equal(head.status, 200); assert.equal(head.headers.get('content-length'), String(AUDIO_DATA.length));
    assert.equal(await head.text(), '');
    const ranged = await fetch(url, { headers: { Range: 'bytes=1-3', 'If-Range': etag } });
    assert.equal(ranged.status, 206); assert.equal(ranged.headers.get('content-range'), `bytes 1-3/${AUDIO_DATA.length}`);
    assert.deepEqual(Buffer.from(await ranged.arrayBuffer()), AUDIO_DATA.subarray(1, 4));
    assert.match(ranged.headers.get('cache-control'), /immutable/);
    const staleRange = await fetch(url, { headers: { Range: 'bytes=1-3', 'If-Range': '"not-the-etag"' } });
    assert.equal(staleRange.status, 200); await staleRange.arrayBuffer();
    const notModified = await fetch(url, { headers: { 'If-None-Match': etag } });
    assert.equal(notModified.status, 304); assert.match(notModified.headers.get('cache-control'), /immutable/);
    assert.equal(notModified.headers.get('access-control-allow-origin'), '*');
    const invalidRange = await fetch(url, { headers: { Range: 'bytes=99999-' } });
    assert.equal(invalidRange.status, 416);
    assert.equal(invalidRange.headers.get('access-control-allow-origin'), '*');
    // Stock Nginx's Range filter can append an error after success headers. no-store MUST win even then.
    assert.match(invalidRange.headers.get('cache-control'), /(?:^|,\s*)no-store(?:,|$)/);
    const options = await fetch(url, { method: 'OPTIONS' }); assert.equal(options.status, 204);
    assert.equal(options.headers.get('access-control-allow-origin'), '*');
    const post = await fetch(url, { method: 'POST' }); assert.equal(post.status, 403);
    assert.equal(post.headers.get('cache-control'), 'no-store');
    for (const ext of AUDIO_EXTS) {
      const res = await fetch(origin + `/releases/${RELEASE}/media/sfx/test${ext.slice(1)}`);
      assert.equal(res.status, 200); assert.equal(res.headers.get('content-type'), AUDIO_MIME[ext]); await res.arrayBuffer();
    }
    for (const ext of AUDIO_EXTS) {
      const res = await fetch(url + ext);
      assert.equal(res.status, 200, ext); assert.equal(res.url, url + ext);
      const actualExt = ext === '.ogg' ? '.ogg' : '.mp3';
      assert.equal(res.headers.get('content-type'), AUDIO_MIME[actualExt], ext);
      assert.equal(await res.text(), ext === '.ogg' ? 'alternate audio' : AUDIO_DATA.toString(), ext);
    }
    const image = await fetch(origin + `/releases/${RELEASE}/assets/ui/%5Bopt%5Dimage.png`);
    assert.equal(image.status, 200); assert.equal(image.headers.get('content-type'), 'image/png'); await image.text();
    const vendor = await fetch(origin + `/releases/${RELEASE}/vendor/hooks.module.js`);
    assert.equal(vendor.status, 200); assert.match(vendor.headers.get('content-type'), /javascript/); await vendor.text();
    await put(join(f.output, 'releases', RELEASE, 'assets/injected.json'), '{"secret":true}');
    for (const path of ['media/bgm/theme.flac', 'media/missing', 'media/', 'assets/', 'assets/injected.json', 'assets/.env', 'data/private.json', '../release-manifest.json']) {
      const res = await fetch(origin + `/releases/${RELEASE}/` + path);
      assert.ok([400, 403, 404].includes(res.status), `${path}: ${res.status}`);
      assert.equal(res.headers.get('cache-control'), 'no-store');
      assert.equal(res.headers.get('access-control-allow-origin'), '*');
      assert.doesNotMatch(await res.text(), /private game code|"secret":true/);
    }
    const traversal = await rawGet(port, `/releases/${RELEASE}/assets/%2e%2e/%2e%2e/%2e%2e/data/private.json`);
    assert.ok([400, 403, 404].includes(traversal.status)); assert.doesNotMatch(traversal.body, /"private":true/);
    const audioFile = join(f.output, 'releases', RELEASE, 'assets/audio/bgm/theme.mp3');
    await rm(audioFile); await symlink(join(f.source, 'public/assets/audio/bgm/theme.mp3'), audioFile);
    const symlinked = await fetch(url); assert.ok([403, 404].includes(symlinked.status));
    assert.equal(symlinked.headers.get('cache-control'), 'no-store');
    const redirect = await fetch(`http://127.0.0.1:${gamePort}/media/bgm/theme?v=123`, { redirect: 'manual' });
    assert.equal(redirect.status, 302);
    assert.equal(redirect.headers.get('location'), `https://ark-asset.hanabi-ai.cn:25442/releases/${RELEASE}/media/bgm/theme?v=123`);
    const code = await fetch(`http://127.0.0.1:${gamePort}/js/gate.js`); assert.equal(code.status, 401);
  });
});

// Opt-in complete art/vendor release; no downloads and no changes to its immutable files.
// NGINX_BIN=<binary> NGINX_MIME_TYPES=<mime.types> NGINX_RELEASE_DIR=<accessible prepared-dir> node --test <this-file>
test('full prepared release Nginx smoke: all whitelist entries, audio mappings and long hash keys', { timeout: 120000 }, async (t) => {
  if (!process.env.NGINX_RELEASE_DIR) { t.skip('Set NGINX_RELEASE_DIR to an already prepared, worker-readable full release'); return; }
  const nginx = nginxBinary(t); if (!nginx) return;
  const output = resolve(process.env.NGINX_RELEASE_DIR);
  const manifest = await verifyStaticRelease(output);
  const base = await mkdtemp(join(tmpdir(), 'ark-static-full-nginx-'));
  await chmod(base, 0o755); t.after(() => rm(base, { recursive: true, force: true }));
  await withNginx(nginx, { output, base }, manifest, async ({ origin, gamePort }) => {
    const prefix = `/releases/${manifest.release}/`;
    const fetchHead = async (path) => {
      const res = await fetch(origin + prefix + path, { method: 'HEAD', headers: { 'Accept-Encoding': 'identity' } });
      assert.equal(res.status, 200, path); assert.match(res.headers.get('cache-control'), /immutable/, path);
      assert.equal(res.headers.get('access-control-allow-origin'), '*', path);
      return res;
    };
    // Bounded concurrent reads exercise every map key, not merely successful config parsing.
    for (let i = 0; i < manifest.files.length; i += 32) {
      await Promise.all(manifest.files.slice(i, i + 32).map(async ({ path, bytes }) => {
        const res = await fetchHead(path);
        assert.equal(res.headers.get('content-length'), String(bytes), path);
      }));
    }
    for (let i = 0; i < manifest.media.length; i += 32) {
      await Promise.all(manifest.media.slice(i, i + 32).map(async ({ url, mime, file }) => {
        const res = await fetchHead(url.slice(1));
        assert.equal(res.headers.get('content-type'), mime, url);
        assert.equal(res.headers.get('content-length'), String(manifest.files.find((entry) => entry.path === file).bytes), url);
      }));
    }
    const first = manifest.media.find(({ requestedExtension }) => !requestedExtension);
    const url = origin + prefix + first.url.slice(1);
    const range = await fetch(url, { headers: { Range: 'bytes=0-15' } });
    assert.equal(range.status, 206); assert.equal((await range.arrayBuffer()).byteLength, 16);
    const cached = await fetch(url, { headers: { 'If-None-Match': range.headers.get('etag') } });
    assert.equal(cached.status, 304); assert.match(cached.headers.get('cache-control'), /immutable/);
    const redirect = await fetch(`http://127.0.0.1:${gamePort}${first.url}?v=check`, { redirect: 'manual' });
    assert.equal(redirect.status, 302);
    assert.equal(redirect.headers.get('location'), `https://ark-asset.hanabi-ai.cn:25442${prefix}${first.url.slice(1)}?v=check`);
    const error = await fetch(origin + prefix + 'media/not-a-track');
    assert.equal(error.status, 404); assert.equal(error.headers.get('cache-control'), 'no-store');
    const stems = manifest.media.filter(({ requestedExtension }) => !requestedExtension).length;
    t.diagnostic(`Verified ${manifest.files.length} exact static files, ${stems} extensionless audio routes and ${manifest.media.length - stems} explicit-suffix aliases with real Nginx`);
  });
});
