if ($ark_beta_play_entry = 1) { return 303 /entry?next=$ark_beta_next; }
proxy_pass http://ark_beta_game_backend;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header CF-Connecting-IP "";
proxy_set_header Forwarded "";
proxy_set_header X-Forwarded-Host "";
proxy_set_header Upgrade $ark_beta_upgrade;
proxy_set_header Connection $ark_beta_connection;
